export const API_REQUEST = "API_REQUEST";
export const API_SUCCESS = "API_SUCCESS";
export const API_ERROR = "API_ERROR";

export const VESSEL_OERATOR_REQUEST = "VTR_LIST_REQUEST";
export const VESSEL_OERATOR_SUCCESS = "VTR_LIST_SUCCESS";
export const VESSEL_OERATOR_ERROR = "VTR_LIST_ERROR";

export const VESSEL_PERMIT_REQUEST = "VTR_LIST_REQUEST";
export const VESSEL_PERMIT_SUCCESS = "VTR_LIST_SUCCESS";
export const VESSEL_PERMIT_ERROR = "VTR_LIST_ERROR";

export const VTR_LIST_REQUEST = "VTR_LIST_REQUEST";
export const VTR_LIST_SUCCESS = "VTR_LIST_SUCCESS";
export const VTR_LIST_ERROR = "VTR_LIST_ERROR";
export const LOAD_IVRS_REQUEST = "LOAD_IVRS_REQUEST";
export const LOAD_IVRS_SUCCESS = "LOAD_IVRS_SUCCESS";
export const LOAD_IVRS_ERROR = "LOAD_IVRS_ERROR";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const UPDATE_SUCCESS_VALIDATIONS = "UPDATE_SUCCESS_VALIDATIONS";
export const UPDATE_ERROR_VALIDATIONS = "UPDATE_ERROR_VALIDATIONS";
